/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './multiple-date-picker.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from './date-range-helper';
export const MultipleDatePickerModuleNgFactory:i0.NgModuleFactory<i1.MultipleDatePickerModule> = i0.ɵcmf(i1.MultipleDatePickerModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i4.DateRangeHelper,i4.DateRangeHelper,
          ([] as any[])),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,([] as any[])),
          i0.ɵmpd(512,i3.ɵba,i3.ɵba,([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i1.MultipleDatePickerModule,i1.MultipleDatePickerModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiZTovRGV2ZWxvcG1lbnQvbXVsdGlwbGUtZGF0ZS1waWNrZXItYW5ndWxhci9zcmMvbXVsdGlwbGUtZGF0ZS1waWNrZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2U6L0RldmVsb3BtZW50L211bHRpcGxlLWRhdGUtcGlja2VyLWFuZ3VsYXIvc3JjL211bHRpcGxlLWRhdGUtcGlja2VyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
