/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './multiple-date-picker.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/forms/src/directives/control_value_accessor';
import * as import10 from './multiple-date-picker.component.css.shim.ngstyle';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../config/node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import13 from '../config/node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '../config/node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import16 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/common/src/directives/ng_class';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from '@angular/common/src/directives/ng_for';
export class Wrapper_MultipleDatePickerComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MultipleDatePickerComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  constructor() {
    this._changed = false;
    this.context = new import0.MultipleDatePickerComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
    this._expr_7 = import1.UNINITIALIZED;
    this._expr_8 = import1.UNINITIALIZED;
    this._expr_9 = import1.UNINITIALIZED;
    this._expr_10 = import1.UNINITIALIZED;
    this._expr_11 = import1.UNINITIALIZED;
    this._expr_12 = import1.UNINITIALIZED;
    this._expr_13 = import1.UNINITIALIZED;
    this._expr_14 = import1.UNINITIALIZED;
    this._expr_15 = import1.UNINITIALIZED;
    this._expr_16 = import1.UNINITIALIZED;
    this._expr_17 = import1.UNINITIALIZED;
    this._expr_18 = import1.UNINITIALIZED;
    this._expr_19 = import1.UNINITIALIZED;
    this._expr_20 = import1.UNINITIALIZED;
    this._expr_21 = import1.UNINITIALIZED;
    this._expr_22 = import1.UNINITIALIZED;
    this._expr_23 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_highlightDays(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.highlightDays = currValue;
      this._expr_0 = currValue;
    }
  }
  check_dayClick(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.dayClick = currValue;
      this._expr_1 = currValue;
    }
  }
  check_dayHover(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.dayHover = currValue;
      this._expr_2 = currValue;
    }
  }
  check_rightClick(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.rightClick = currValue;
      this._expr_3 = currValue;
    }
  }
  check_month(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.month = currValue;
      this._expr_4 = currValue;
    }
  }
  check_monthChanged(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_5,currValue))) {
      this._changed = true;
      this.context.monthChanged = currValue;
      this._expr_5 = currValue;
    }
  }
  check_monthClick(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_6,currValue))) {
      this._changed = true;
      this.context.monthClick = currValue;
      this._expr_6 = currValue;
    }
  }
  check_weekDaysOff(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_7,currValue))) {
      this._changed = true;
      this.context.weekDaysOff = currValue;
      this._expr_7 = currValue;
    }
  }
  check_allDaysOff(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_8,currValue))) {
      this._changed = true;
      this.context.allDaysOff = currValue;
      this._expr_8 = currValue;
    }
  }
  check_daysAllowed(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_9,currValue))) {
      this._changed = true;
      this.context.daysAllowed = currValue;
      this._expr_9 = currValue;
    }
  }
  check_disableNavigation(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_10,currValue))) {
      this._changed = true;
      this.context.disableNavigation = currValue;
      this._expr_10 = currValue;
    }
  }
  check_disallowBackPastMonths(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_11,currValue))) {
      this._changed = true;
      this.context.disallowBackPastMonths = currValue;
      this._expr_11 = currValue;
    }
  }
  check_disallowGoFuturMonths(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_12,currValue))) {
      this._changed = true;
      this.context.disallowGoFuturMonths = currValue;
      this._expr_12 = currValue;
    }
  }
  check_showDaysOfSurroundingMonths(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_13,currValue))) {
      this._changed = true;
      this.context.showDaysOfSurroundingMonths = currValue;
      this._expr_13 = currValue;
    }
  }
  check_cssDaysOfSurroundingMonths(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_14,currValue))) {
      this._changed = true;
      this.context.cssDaysOfSurroundingMonths = currValue;
      this._expr_14 = currValue;
    }
  }
  check_fireEventsForDaysOfSurroundingMonths(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_15,currValue))) {
      this._changed = true;
      this.context.fireEventsForDaysOfSurroundingMonths = currValue;
      this._expr_15 = currValue;
    }
  }
  check_disableDaysBefore(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_16,currValue))) {
      this._changed = true;
      this.context.disableDaysBefore = currValue;
      this._expr_16 = currValue;
    }
  }
  check_disableDaysAfter(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_17,currValue))) {
      this._changed = true;
      this.context.disableDaysAfter = currValue;
      this._expr_17 = currValue;
    }
  }
  check_changeYearPast(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_18,currValue))) {
      this._changed = true;
      this.context.changeYearPast = currValue;
      this._expr_18 = currValue;
    }
  }
  check_changeYearFuture(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_19,currValue))) {
      this._changed = true;
      this.context.changeYearFuture = currValue;
      this._expr_19 = currValue;
    }
  }
  check_projectScope(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_20,currValue))) {
      this._changed = true;
      this.context.projectScope = currValue;
      this._expr_20 = currValue;
    }
  }
  check_something(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_21,currValue))) {
      this._changed = true;
      this.context.something = currValue;
      this._expr_21 = currValue;
    }
  }
  check_sundayFirstDay(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_22,currValue))) {
      this._changed = true;
      this.context.sundayFirstDay = currValue;
      this._expr_22 = currValue;
    }
  }
  check__projectScope(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_23,currValue))) {
      this._changed = true;
      this.context._projectScope = currValue;
      this._expr_23 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MultipleDatePickerComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_MultipleDatePickerComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.MultipleDatePickerComponent>;
  _MultipleDatePickerComponent_0_3:Wrapper_MultipleDatePickerComponent;
  __NG_VALUE_ACCESSOR_0_4:any[];
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MultipleDatePickerComponent_Host0,renderType_MultipleDatePickerComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_0_4():any[] {
    if ((this.__NG_VALUE_ACCESSOR_0_4 == null)) { (this.__NG_VALUE_ACCESSOR_0_4 = [this._MultipleDatePickerComponent_0_3.context]); }
    return this.__NG_VALUE_ACCESSOR_0_4;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'multiple-date-picker',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MultipleDatePickerComponent0(this.viewUtils,this,0,this._el_0);
    this._MultipleDatePickerComponent_0_3 = new Wrapper_MultipleDatePickerComponent();
    this.compView_0.create(this._MultipleDatePickerComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._MultipleDatePickerComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MultipleDatePickerComponent) && (0 === requestNodeIndex))) { return this._MultipleDatePickerComponent_0_3.context; }
    if (((token === import9.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MultipleDatePickerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MultipleDatePickerComponentNgFactory:import8.ComponentFactory<import0.MultipleDatePickerComponent> = new import8.ComponentFactory<import0.MultipleDatePickerComponent>('multiple-date-picker',View_MultipleDatePickerComponent_Host0,import0.MultipleDatePickerComponent);
const styles_MultipleDatePickerComponent:any[] = [import10.styles];
class View_MultipleDatePickerComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_MultipleDatePickerComponent1,renderType_MultipleDatePickerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.yearToDisplay,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_MultipleDatePickerComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_MultipleDatePickerComponent2,renderType_MultipleDatePickerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_MultipleDatePickerComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_MultipleDatePickerComponent3,renderType_MultipleDatePickerComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'text-center picker-day ',this.parentView.context.getDayClasses(this.context.$implicit),'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'className',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_0,'title',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import3.inlineInterpolate(1,'\n            ',(this.context.$implicit? ((this.context.$implicit.mdp.otherMonth && !this.parentView.context.showDaysOfSurroundingMonths)? ' ': this.context.$implicit.date.format('D')): ''),'\n        ');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.toggleDay($event,this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_MultipleDatePickerComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_MultipleDatePickerComponent,{});
export class View_MultipleDatePickerComponent0 extends import2.AppView<import0.MultipleDatePickerComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _NgClass_4_3:import12.Wrapper_NgClass;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _vc_9:import11.ViewContainer;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import13.Wrapper_NgIf;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _NgClass_12_3:import12.Wrapper_NgClass;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _vc_33:import11.ViewContainer;
  _TemplateRef_33_5:any;
  _NgFor_33_6:import14.Wrapper_NgFor;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _anchor_38:any;
  /*private*/ _vc_38:import11.ViewContainer;
  _TemplateRef_38_5:any;
  _NgFor_38_6:import14.Wrapper_NgFor;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _map_58:any;
  /*private*/ _expr_59:any;
  _map_60:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MultipleDatePickerComponent0,renderType_MultipleDatePickerComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._map_58 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {disabled: p0};
    });
    this._expr_59 = import1.UNINITIALIZED;
    this._map_60 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {disabled: p0};
    });
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','multiple-date-picker'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','picker-top-row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','text-center picker-navigate picker-navigate-left-arrow'),(null as any));
    this._NgClass_4_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import15.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import16.KeyValueDiffers,this.parentIndex),new import17.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'<',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','text-center picker-month'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._vc_9 = new import11.ViewContainer(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import18.TemplateRef_(this,9,this._anchor_9);
    this._NgIf_9_6 = new import13.Wrapper_NgIf(this._vc_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','text-center picker-navigate picker-navigate-right-arrow'),(null as any));
    this._NgClass_12_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import15.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import16.KeyValueDiffers,this.parentIndex),new import17.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText(this._el_12,'>',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_2,'button',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Clear Days',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_2,'button',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Log Days',(null as any));
    this._text_20 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_2,'button',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Find Array',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_2,'button',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n        Decrement\n      ',(null as any));
    this._text_26 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_2,'button',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n        Increment\n      ',(null as any));
    this._text_29 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','picker-days-week-row'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_31,(null as any));
    this._vc_33 = new import11.ViewContainer(33,31,this,this._anchor_33);
    this._TemplateRef_33_5 = new import18.TemplateRef_(this,33,this._anchor_33);
    this._NgFor_33_6 = new import14.Wrapper_NgFor(this._vc_33.vcRef,this._TemplateRef_33_5,this.parentView.injectorGet(import15.IterableDiffers,this.parentIndex),this.ref);
    this._text_34 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','picker-days-row'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._anchor_38 = this.renderer.createTemplateAnchor(this._el_36,(null as any));
    this._vc_38 = new import11.ViewContainer(38,36,this,this._anchor_38);
    this._TemplateRef_38_5 = new import18.TemplateRef_(this,38,this._anchor_38);
    this._NgFor_38_6 = new import14.Wrapper_NgFor(this._vc_38.vcRef,this._TemplateRef_38_5,this.parentView.injectorGet(import15.IterableDiffers,this.parentIndex),this.ref);
    this._text_39 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_41 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_43 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_44 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_45 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_46 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_21,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_21));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_24));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_27));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._anchor_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.NgClass) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._NgClass_4_3.context; }
    if (((token === import18.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import20.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6.context; }
    if (((token === import19.NgClass) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgClass_12_3.context; }
    if (((token === import18.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import21.NgFor) && (33 === requestNodeIndex))) { return this._NgFor_33_6.context; }
    if (((token === import18.TemplateRef) && (38 === requestNodeIndex))) { return this._TemplateRef_38_5; }
    if (((token === import21.NgFor) && (38 === requestNodeIndex))) { return this._NgFor_38_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = 'text-center picker-navigate picker-navigate-left-arrow';
    this._NgClass_4_3.check_klass(currVal_4_0_0,throwOnChange,false);
    const currVal_4_0_1:any = this._map_58(this.context.disableBackButton);
    this._NgClass_4_3.check_ngClass(currVal_4_0_1,throwOnChange,false);
    this._NgClass_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_9_0_0:any = (this.context.yearsForSelect.length < 2);
    this._NgIf_9_6.check_ngIf(currVal_9_0_0,throwOnChange,false);
    this._NgIf_9_6.ngDoCheck(this,this._anchor_9,throwOnChange);
    const currVal_12_0_0:any = 'text-center picker-navigate picker-navigate-right-arrow';
    this._NgClass_12_3.check_klass(currVal_12_0_0,throwOnChange,false);
    const currVal_12_0_1:any = this._map_60(this.context.disableNextButton);
    this._NgClass_12_3.check_ngClass(currVal_12_0_1,throwOnChange,false);
    this._NgClass_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_33_0_0:any = this.context.daysOfWeek;
    this._NgFor_33_6.check_ngForOf(currVal_33_0_0,throwOnChange,false);
    this._NgFor_33_6.ngDoCheck(this,this._anchor_33,throwOnChange);
    const currVal_38_0_0:any = this.context.days;
    this._NgFor_38_6.check_ngForOf(currVal_38_0_0,throwOnChange,false);
    this._NgFor_38_6.ngDoCheck(this,this._anchor_38,throwOnChange);
    this._vc_9.detectChangesInNestedViews(throwOnChange);
    this._vc_33.detectChangesInNestedViews(throwOnChange);
    this._vc_38.detectChangesInNestedViews(throwOnChange);
    const currVal_59:any = import3.inlineInterpolate(1,'\n            ',this.context.monthToDisplay,'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setText(this._text_8,currVal_59);
      this._expr_59 = currVal_59;
    }
  }
  destroyInternal():void {
    this._vc_9.destroyNestedViews();
    this._vc_33.destroyNestedViews();
    this._vc_38.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 9)) { return new View_MultipleDatePickerComponent1(this.viewUtils,this,9,this._anchor_9,this._vc_9); }
    if ((nodeIndex == 33)) { return new View_MultipleDatePickerComponent2(this.viewUtils,this,33,this._anchor_33,this._vc_33); }
    if ((nodeIndex == 38)) { return new View_MultipleDatePickerComponent3(this.viewUtils,this,38,this._anchor_38,this._vc_38); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changeMonth($event,this.context.disableBackButton,(0 - 1))) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changeMonth($event,this.context.disableNextButton,1)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.clearDays()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.logDays()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_21(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.findArray()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.decrement()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.increment()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}